name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t shivalika/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true shivalika/react-test npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Docker-repo
          environment_name: Docker-repo-env
          existing_bucket_name: elasticbeanstalk-eu-west-1-800443831915
          region: eu-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip